package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.AttachmentAudit;

public interface AttachmentAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_audit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_audit
     *
     * @mbg.generated
     */
    int insert(AttachmentAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_audit
     *
     * @mbg.generated
     */
    AttachmentAudit selectByPrimaryKey(BigInteger attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_audit
     *
     * @mbg.generated
     */
    List<AttachmentAudit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_audit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AttachmentAudit record);

	int replace(AttachmentAudit attachmentAudit);
}