package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.dto.CertificateDto;
import top.warmheart.workerunion.server.model.Certificate;

public interface CertificateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbg.generated
     */
    int insert(Certificate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbg.generated
     */
    Certificate selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbg.generated
     */
    List<Certificate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Certificate record);

	int deleteById(BigInteger id);

	CertificateDto selectDetailById(BigInteger id);

	Integer countByFuzzy(@Param("certificateDto")CertificateDto certificateDto);

	List<CertificateDto> pageByFuzzy(@Param("certificateDto")CertificateDto certificateDto,@Param("page") Page<?> page);

	List<Certificate> selectListByStaffId(BigInteger staffId);
}