package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.CertificateSerie;

public interface CertificateSerieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_serie
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_serie
     *
     * @mbg.generated
     */
    int insert(CertificateSerie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_serie
     *
     * @mbg.generated
     */
    CertificateSerie selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_serie
     *
     * @mbg.generated
     */
    List<CertificateSerie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_serie
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CertificateSerie record);
}