package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.CertificateType;

public interface CertificateTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_type
     *
     * @mbg.generated
     */
    int insert(CertificateType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_type
     *
     * @mbg.generated
     */
    CertificateType selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_type
     *
     * @mbg.generated
     */
    List<CertificateType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CertificateType record);

	List<CertificateType> selectListBySerieId(BigInteger certificateSerieId);
}