package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.ContractAttachment;

public interface ContractAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbg.generated
     */
    int insert(ContractAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbg.generated
     */
    ContractAttachment selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbg.generated
     */
    List<ContractAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContractAttachment record);

	int deleteById(BigInteger attachmentId);

	List<ContractAttachment> selectListByContractId(BigInteger contractId);
}