package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import top.warmheart.workerunion.server.model.CostAnalysisItemDeepen;

public interface CostAnalysisItemDeepenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_analysis_item_deepen
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_analysis_item_deepen
     *
     * @mbg.generated
     */
    int insert(CostAnalysisItemDeepen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_analysis_item_deepen
     *
     * @mbg.generated
     */
    CostAnalysisItemDeepen selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_analysis_item_deepen
     *
     * @mbg.generated
     */
    List<CostAnalysisItemDeepen> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_analysis_item_deepen
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CostAnalysisItemDeepen record);
	/**
	 * 获取项目下的所有成本深化项
	 * 
	 * @param projectId
	 * @return
	 */
	List<CostAnalysisItemDeepen> selectListByProjectId(BigInteger projectId);

	CostAnalysisItemDeepen selectByPrimaryKey4Update(BigInteger id);
}