package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.FinalSettlementItemAttachment;

public interface FinalSettlementItemAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger finalSettlementItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item_attachment
     *
     * @mbg.generated
     */
    int insert(FinalSettlementItemAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item_attachment
     *
     * @mbg.generated
     */
    FinalSettlementItemAttachment selectByPrimaryKey(BigInteger finalSettlementItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item_attachment
     *
     * @mbg.generated
     */
    List<FinalSettlementItemAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FinalSettlementItemAttachment record);
}