package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import top.warmheart.workerunion.server.dto.FinalSettlementItemDto;
import top.warmheart.workerunion.server.model.FinalSettlementItem;

public interface FinalSettlementItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item
     *
     * @mbg.generated
     */
    int insert(FinalSettlementItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item
     *
     * @mbg.generated
     */
    FinalSettlementItem selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item
     *
     * @mbg.generated
     */
    List<FinalSettlementItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FinalSettlementItem record);

	List<FinalSettlementItemDto> selectListByProjectId(BigInteger projectId);

	int deleteById(BigInteger id);
}