package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import top.warmheart.workerunion.server.dto.FundPlanItemDto;
import top.warmheart.workerunion.server.model.FundPlanItem;

public interface FundPlanItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_plan_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_plan_item
     *
     * @mbg.generated
     */
    int insert(FundPlanItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_plan_item
     *
     * @mbg.generated
     */
    FundPlanItem selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_plan_item
     *
     * @mbg.generated
     */
    List<FundPlanItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_plan_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FundPlanItem record);

	List<FundPlanItemDto> selectListByProjectId(BigInteger projectId);

	FundPlanItem selectByPrimaryKey4Update(BigInteger fundPlanItemId);

	List<FundPlanItem> selectListByCostAnalysisItemId(BigInteger costAnalysisItemId);

	List<FundPlanItem> selectListSimpleByProjectId(BigInteger projectId);
}