package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.model.MaterialType;

public interface MaterialTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated
     */
    int insert(MaterialType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated
     */
    MaterialType selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated
     */
    List<MaterialType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialType record);

	MaterialType selectByCompanyAndNum(@Param("companyId")BigInteger companyId,@Param("num") String num);

	int deleteById(BigInteger id);

	Integer countByFuzzy(@Param("materialType")MaterialType materialType);

	List<MaterialType> pageByFuzzy(@Param("materialType")MaterialType materialType,@Param("page") Page<MaterialType> pageCheck);
}