package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.dto.MaterialTransferApplicationDto;
import top.warmheart.workerunion.server.model.MaterialTransferApplication;

public interface MaterialTransferApplicationMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_transfer_application
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_transfer_application
	 *
	 * @mbg.generated
	 */
	int insert(MaterialTransferApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_transfer_application
	 *
	 * @mbg.generated
	 */
	MaterialTransferApplication selectByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_transfer_application
	 *
	 * @mbg.generated
	 */
	List<MaterialTransferApplication> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_transfer_application
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MaterialTransferApplication record);

	Integer countByFuzzy(
			@Param("materialTransferApplicationDto") MaterialTransferApplicationDto materialTransferApplicationDto);

	List<MaterialTransferApplicationDto> pageByFuzzy(
			@Param("materialTransferApplicationDto") MaterialTransferApplicationDto materialTransferApplicationDto,
			@Param("page") Page<MaterialTransferApplicationDto> page);

	MaterialTransferApplicationDto selectDetailById(BigInteger id);

	List<MaterialTransferApplicationDto> selectListByCompanyId(@Param("companyId") BigInteger companyId,
			@Param("status") String status);

	MaterialTransferApplication selectByPrimaryKey4Update(BigInteger id);
}