package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.model.MaterialHeadquartersOrder;

public interface MaterialHeadquartersOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order
     *
     * @mbg.generated
     */
    int insert(MaterialHeadquartersOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order
     *
     * @mbg.generated
     */
    MaterialHeadquartersOrder selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order
     *
     * @mbg.generated
     */
    List<MaterialHeadquartersOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialHeadquartersOrder record);

	Integer countByFuzzy(@Param("companyId")BigInteger companyId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo);

	List<MaterialHeadquartersOrder> pageByFuzzy(@Param("companyId")BigInteger companyId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo,@Param("page") Page<?> page);

	MaterialHeadquartersOrder selectByCompanyBatchNo(@Param("companyId")BigInteger companyId,@Param("batchNo") String batchNo);

}