package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.model.MaterialOrder;

public interface MaterialOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_order
     *
     * @mbg.generated
     */
    int insert(MaterialOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_order
     *
     * @mbg.generated
     */
    MaterialOrder selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_order
     *
     * @mbg.generated
     */
    List<MaterialOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialOrder record);

	Integer countByFuzzy(@Param("projectId")BigInteger projectId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo);

	List<MaterialOrder> pageByFuzzy(@Param("projectId")BigInteger projectId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo,@Param("page") Page<?> page);

	MaterialOrder selectByProjectBatchNo(@Param("projectId")BigInteger projectId,@Param("batchNo") String batchNo);

}