package top.warmheart.workerunion.server.dao;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.dto.MaterialOrderDetail2Dto;
import top.warmheart.workerunion.server.model.MaterialOrderDetail;

public interface MaterialOrderDetailMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_order_detail
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_order_detail
	 *
	 * @mbg.generated
	 */
	int insert(MaterialOrderDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_order_detail
	 *
	 * @mbg.generated
	 */
	MaterialOrderDetail selectByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_order_detail
	 *
	 * @mbg.generated
	 */
	List<MaterialOrderDetail> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table material_order_detail
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MaterialOrderDetail record);

	BigDecimal amountByType(@Param("projectId") BigInteger projectId, @Param("num") String num,
			@Param("type") String type);

	Integer countByNum(@Param("projectId") BigInteger projectId, @Param("num") String num);

	List<MaterialOrderDetail2Dto> pageByNum(@Param("projectId") BigInteger projectId, @Param("num") String num,
			@Param("page") Page<?> page);

	Integer countByFuzzy(@Param("projectId")BigInteger projectId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo);

	List<MaterialOrderDetail2Dto> pageByFuzzy(@Param("projectId")BigInteger projectId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo,@Param("page") Page<?> page);
}