package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.MaterialTransferApplicationDetail;

public interface MaterialTransferApplicationDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_transfer_application_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_transfer_application_detail
     *
     * @mbg.generated
     */
    int insert(MaterialTransferApplicationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_transfer_application_detail
     *
     * @mbg.generated
     */
    MaterialTransferApplicationDetail selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_transfer_application_detail
     *
     * @mbg.generated
     */
    List<MaterialTransferApplicationDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_transfer_application_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialTransferApplicationDetail record);

	List<MaterialTransferApplicationDetail> selectListByApplicationId(BigInteger transferApplicationId);

	List<MaterialTransferApplicationDetail> selectListByApplicationId4Update(BigInteger transferApplicationId);
}