package top.warmheart.workerunion.server.dao;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.dto.MaterialHeadquartersOrderDetail2Dto;
import top.warmheart.workerunion.server.model.MaterialHeadquartersOrderDetail;

public interface MaterialHeadquartersOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order_detail
     *
     * @mbg.generated
     */
    int insert(MaterialHeadquartersOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order_detail
     *
     * @mbg.generated
     */
    MaterialHeadquartersOrderDetail selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order_detail
     *
     * @mbg.generated
     */
    List<MaterialHeadquartersOrderDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialHeadquartersOrderDetail record);

	BigDecimal amountByType(@Param("companyId") BigInteger companyId, @Param("num") String num,
			@Param("type") String type);

	Integer countByNum(@Param("companyId") BigInteger companyId, @Param("num") String num);

	List<MaterialHeadquartersOrderDetail2Dto> pageByNum(@Param("companyId") BigInteger companyId, @Param("num") String num,
			@Param("page") Page<?> page);

	Integer countByFuzzy(@Param("companyId")BigInteger companyId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo);

	List<MaterialHeadquartersOrderDetail2Dto> pageByFuzzy(@Param("companyId")BigInteger companyId,@Param("staffName") String staffName,@Param("cstCreate") Date cstCreate,@Param("batchNo") String batchNo,@Param("page") Page<?> page);


}