package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.model.Material;

public interface MaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    Material selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    List<Material> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Material record);

	Integer countByFuzzy(@Param("projectId")BigInteger projectId,@Param("num") String num,@Param("name") String name);

	List<Material> pageByFuzzy(@Param("projectId")BigInteger projectId,@Param("num") String num,@Param("name") String name,@Param("page") Page<?> page);

	Material selectByNum(@Param("projectId")BigInteger projectId,@Param("num") String num);

	int insertOrAccumulate(Material material);

	Material selectByNum4Update(@Param("projectId")BigInteger projectId,@Param("num") String num);
}