package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.model.ProductCapacityItem;

public interface ProductCapacityItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_capacity_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_capacity_item
     *
     * @mbg.generated
     */
    int insert(ProductCapacityItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_capacity_item
     *
     * @mbg.generated
     */
    ProductCapacityItem selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_capacity_item
     *
     * @mbg.generated
     */
    List<ProductCapacityItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_capacity_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductCapacityItem record);

    ProductCapacityItem selectByProjectYearMonth(@Param("projectId")BigInteger projectId,@Param("year") Integer year,@Param("month") Integer month);

	Integer countByProjectId(BigInteger projectId);

	List<ProductCapacityItem> pageByProjectId(@Param("projectId")BigInteger projectId,@Param("page") Page<ProductCapacityItem> page);

}