package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.workerunion.server.dto.Staff3Dto;
import top.warmheart.workerunion.server.model.ProjectTeam;

public interface ProjectTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("projectId") BigInteger projectId, @Param("staffId") BigInteger staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team
     *
     * @mbg.generated
     */
    int insert(ProjectTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team
     *
     * @mbg.generated
     */
    ProjectTeam selectByPrimaryKey(@Param("projectId") BigInteger projectId, @Param("staffId") BigInteger staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team
     *
     * @mbg.generated
     */
    List<ProjectTeam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectTeam record);

	ProjectTeam selectByProjectRole(@Param("projectId")BigInteger projectId,@Param("teamRoleId") BigInteger teamRoleId);

	List<Staff3Dto> selectListStaffByProjectId(BigInteger projectId);

	Staff3Dto selectByProjectTeamType(@Param("projectId")BigInteger projectId,@Param("type") String type);
}