package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.PurchaseItem;

public interface PurchaseItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int insert(PurchaseItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    PurchaseItem selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    List<PurchaseItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PurchaseItem record);

	List<PurchaseItem> selectList();
}