package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import top.warmheart.workerunion.server.model.QualityCheckItemAttachment;

public interface QualityCheckItemAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_check_item_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_check_item_attachment
     *
     * @mbg.generated
     */
    int insert(QualityCheckItemAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_check_item_attachment
     *
     * @mbg.generated
     */
    QualityCheckItemAttachment selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_check_item_attachment
     *
     * @mbg.generated
     */
    List<QualityCheckItemAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quality_check_item_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QualityCheckItemAttachment record);
    
    List<QualityCheckItemAttachment> selectListByItemId(BigInteger itemId);

	int deleteById(BigInteger attachmentId);
}