package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.warmheart.workerunion.server.model.RoleHasPermission;

public interface RoleHasPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleId") BigInteger roleId, @Param("permissionId") BigInteger permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_permission
     *
     * @mbg.generated
     */
    int insert(RoleHasPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_permission
     *
     * @mbg.generated
     */
    List<RoleHasPermission> selectAll();
}