package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.dto.SafetyCheckItemDto;
import top.warmheart.workerunion.server.model.SafetyCheckItem;

public interface SafetyCheckItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item
     *
     * @mbg.generated
     */
    int insert(SafetyCheckItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item
     *
     * @mbg.generated
     */
    SafetyCheckItem selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item
     *
     * @mbg.generated
     */
    List<SafetyCheckItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SafetyCheckItem record);

	Integer countByProjectId(BigInteger projectId);

	List<SafetyCheckItem> pageByProjectId(@Param("projectId")BigInteger projectId,@Param("page") Page<?> page);

	int deleteById(BigInteger id);

	List<SafetyCheckItemDto> selectListByCompanyAndStatus(@Param("companyId")BigInteger companyId,@Param("rectifyStatus") String rectifyStatus);
}