package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.SafetyCheckItemAttachment;

public interface SafetyCheckItemAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item_attachment
     *
     * @mbg.generated
     */
    int insert(SafetyCheckItemAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item_attachment
     *
     * @mbg.generated
     */
    SafetyCheckItemAttachment selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item_attachment
     *
     * @mbg.generated
     */
    List<SafetyCheckItemAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_check_item_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SafetyCheckItemAttachment record);

	List<SafetyCheckItemAttachment> selectListByItemId(BigInteger itemId);

	int deleteById(BigInteger attachmentId);
}