package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.dto.SettlementItem2Dto;
import top.warmheart.workerunion.server.dto.SettlementItemDto;
import top.warmheart.workerunion.server.model.SettlementItem;

public interface SettlementItemMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table settlement_item
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table settlement_item
	 *
	 * @mbg.generated
	 */
	int insert(SettlementItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table settlement_item
	 *
	 * @mbg.generated
	 */
	SettlementItem selectByPrimaryKey(BigInteger id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table settlement_item
	 *
	 * @mbg.generated
	 */
	List<SettlementItem> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table settlement_item
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SettlementItem record);

	List<SettlementItem> selectListByResourceImplementItemId(BigInteger resourceImplementItemId);

	List<SettlementItemDto> pageByProjectId(@Param("projectId")BigInteger projectId,@Param("page") Page<?> page);

	SettlementItem selectByResourceImplementYearMonth(@Param("resourceImplementItemId")BigInteger resourceImplementItemId,@Param("year") Integer year,@Param("month") Integer month);

	Integer countByProjectId(BigInteger projectId);

	SettlementItem2Dto selectDetailById(BigInteger id);
}