package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import top.warmheart.server.util.dto.Page;
import top.warmheart.workerunion.server.dto.SubcontractorDto;
import top.warmheart.workerunion.server.model.Subcontractor;

public interface SubcontractorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor
     *
     * @mbg.generated
     */
    int insert(Subcontractor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor
     *
     * @mbg.generated
     */
    Subcontractor selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor
     *
     * @mbg.generated
     */
    List<Subcontractor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Subcontractor record);

	List<Subcontractor> selectListSimpleItemByCompanyId(BigInteger companyId);

	Subcontractor selectByCompanyAndNum(@Param("companyId")BigInteger companyId,@Param("num") String num);

	int deleteById(BigInteger id);

	Integer countByFuzzy(@Param("subcontractorDto")SubcontractorDto subcontractorDto);

	List<SubcontractorDto> pageByFuzzy(@Param("subcontractorDto")SubcontractorDto subcontractorDto,@Param("page") Page<?> page);
}