package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.SubcontractorAttachment;

public interface SubcontractorAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_attachment
     *
     * @mbg.generated
     */
    int insert(SubcontractorAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_attachment
     *
     * @mbg.generated
     */
    SubcontractorAttachment selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_attachment
     *
     * @mbg.generated
     */
    List<SubcontractorAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubcontractorAttachment record);

	List<SubcontractorAttachment> selectListBySubcontractorId(BigInteger subcontractorId);

	int deleteById(BigInteger attachmentId);
}