package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.SubcontractorQualification;

public interface SubcontractorQualificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_qualification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_qualification
     *
     * @mbg.generated
     */
    int insert(SubcontractorQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_qualification
     *
     * @mbg.generated
     */
    SubcontractorQualification selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_qualification
     *
     * @mbg.generated
     */
    List<SubcontractorQualification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_qualification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubcontractorQualification record);

	List<SubcontractorQualification> selectListBySubcontractorId(BigInteger subcontractorId);
}