package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.warmheart.workerunion.server.model.SupplierHasSupplierQualification;

public interface SupplierHasSupplierQualificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_has_supplier_qualification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("supplierId") BigInteger supplierId, @Param("supplierQualificationId") BigInteger supplierQualificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_has_supplier_qualification
     *
     * @mbg.generated
     */
    int insert(SupplierHasSupplierQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_has_supplier_qualification
     *
     * @mbg.generated
     */
    List<SupplierHasSupplierQualification> selectAll();

	int deleteBySupplierId(BigInteger supplierId);
}