package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.SupplierQualification;

public interface SupplierQualificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_qualification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_qualification
     *
     * @mbg.generated
     */
    int insert(SupplierQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_qualification
     *
     * @mbg.generated
     */
    SupplierQualification selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_qualification
     *
     * @mbg.generated
     */
    List<SupplierQualification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_qualification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SupplierQualification record);

	List<SupplierQualification> selectListBySupplierId(BigInteger supplierId);

}