package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.SupplierGrade;

public interface SupplierGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_grade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_grade
     *
     * @mbg.generated
     */
    int insert(SupplierGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_grade
     *
     * @mbg.generated
     */
    SupplierGrade selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_grade
     *
     * @mbg.generated
     */
    List<SupplierGrade> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_grade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SupplierGrade record);
}