package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.SupplierAttachment;

public interface SupplierAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_attachment
     *
     * @mbg.generated
     */
    int insert(SupplierAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_attachment
     *
     * @mbg.generated
     */
    SupplierAttachment selectByPrimaryKey(BigInteger id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_attachment
     *
     * @mbg.generated
     */
    List<SupplierAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SupplierAttachment record);

	List<SupplierAttachment> selectListBySupplierId(BigInteger supplierId);

	int deleteById(BigInteger attachmentId);
}