package top.warmheart.workerunion.server.dao;

import java.math.BigInteger;
import java.util.List;
import top.warmheart.workerunion.server.model.Target;

public interface TargetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigInteger projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated
     */
    int insert(Target record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated
     */
    Target selectByPrimaryKey(BigInteger projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated
     */
    List<Target> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Target record);

	int replace(Target target);
}