-- MySQL Script generated by MySQL Workbench
-- 06/16/17 20:43:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema worker_union
-- -----------------------------------------------------
-- 工友盟
DROP SCHEMA IF EXISTS `worker_union` ;

-- -----------------------------------------------------
-- Schema worker_union
--
-- 工友盟
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `worker_union` DEFAULT CHARACTER SET utf8 ;
USE `worker_union` ;

-- -----------------------------------------------------
-- Table `worker_union`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`company` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`company` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '企业ID',
  `name` VARCHAR(512) NOT NULL COMMENT '企业名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '企业';


-- -----------------------------------------------------
-- Table `worker_union`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`project` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`project` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL,
  `num` VARCHAR(32) NOT NULL COMMENT '项目编号',
  `name` VARCHAR(512) NOT NULL COMMENT '项目名称',
  `constructer_name` VARCHAR(512) NOT NULL COMMENT '建设方名称',
  `designer_name` VARCHAR(512) NOT NULL COMMENT '设计方名称',
  `superviser_name` VARCHAR(512) NOT NULL COMMENT '监理方名称',
  `address` VARCHAR(512) NOT NULL COMMENT '工程地点',
  `type` VARCHAR(32) NOT NULL COMMENT '工程类型',
  `scale` VARCHAR(1024) NOT NULL COMMENT '工程规模',
  `bid_duration` INT NOT NULL COMMENT '中标工期（单元：天）',
  `file_status` VARCHAR(32) NOT NULL COMMENT '项目状态（进行中:GOING，已归档：ARCHIVED）',
  `collapse_status` VARCHAR(32) NOT NULL COMMENT '解体状态（运行中：GOING，已解体：COLLAPSED）',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `bid_price` DECIMAL(20,2) NOT NULL COMMENT '中标价（单位：元）',
  `memo` VARCHAR(1024) NOT NULL COMMENT '备注',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_num` (`company_id` ASC, `num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '企业项目';


-- -----------------------------------------------------
-- Table `worker_union`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`staff` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`staff` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '企业员工ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `name` VARCHAR(32) NOT NULL COMMENT '姓名',
  `sex` VARCHAR(32) NOT NULL COMMENT '性别（MALE/FEMALE）',
  `job_no` VARCHAR(32) NOT NULL COMMENT '工号',
  `native_place` VARCHAR(32) NOT NULL COMMENT '籍贯',
  `phone` VARCHAR(32) NOT NULL COMMENT '联系方式',
  `id_card_no` VARCHAR(32) NOT NULL COMMENT '身份证号码',
  `address` VARCHAR(512) NOT NULL COMMENT '家庭住址',
  `entry_date` DATE NOT NULL COMMENT '入职时间',
  `career` VARCHAR(10240) NOT NULL COMMENT '职业经历',
  `birthday` DATE NOT NULL COMMENT '生日',
  `salt` VARCHAR(32) NOT NULL COMMENT '盐',
  `password` VARCHAR(32) NOT NULL COMMENT '密码',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `memo` VARCHAR(1024) NOT NULL COMMENT '备注',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_job_no` (`company_id` ASC, `job_no` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '企业员工信息';


-- -----------------------------------------------------
-- Table `worker_union`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（中标通知书：LETTER_OF_ACCEPTANCE，成本分析表：COST_ANALYSIS，目标协议书：AGREEMENT_OF_TARGET，合同备案表：CONTRACT_RECORD，质检通知书：QUALITY_INSPECT_NOTICE，安监登记表：SAFETY_SUPERVISION_FORM，施工许可证：CONSTRUCTION_PERMIT，合同：CONTRACT，成本深化表：COST_DEEPEN，经营管理产值文件：BUSINESS_CAPACITY_FILE，生产管理产值文件：PRODUCT_CAPACITY_FILE，技术方案：TECHNICAL_PROPOSAL，总结报告：FINAL_REPORT，内部结算文件：INTERNAL_SETTLEMENT_FILE，结算文件：SETTLEMENT_FILE，竣工资料：COMPLETION_DATA）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目附件';


-- -----------------------------------------------------
-- Table `worker_union`.`cost_analysis_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`cost_analysis_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`cost_analysis_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '成本分析项ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `name` VARCHAR(32) NOT NULL COMMENT '成本项名称',
  `type` VARCHAR(32) NOT NULL COMMENT '成本类型（直接成本：DIRECT_COST，间接成本：INDIRECT_COST，指定分包成本：SUBCONTRACT_COST，税额：TAX_COST）',
  `cost` DECIMAL(20,2) NOT NULL COMMENT '成本花费（单位：元）',
  `memo` VARCHAR(1024) NOT NULL COMMENT '备注',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目成本分析';


-- -----------------------------------------------------
-- Table `worker_union`.`regional_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`regional_code` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`regional_code` (
  `code` VARCHAR(32) NOT NULL COMMENT '代码',
  `value` VARCHAR(32) NOT NULL COMMENT '行政代码对应地区名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '地区代码';


-- -----------------------------------------------------
-- Table `worker_union`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`role` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`role` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `name` VARCHAR(32) NOT NULL COMMENT '名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '角色';


-- -----------------------------------------------------
-- Table `worker_union`.`target`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`target` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`target` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `duration` INT NOT NULL COMMENT '工期目标',
  `start_date` DATE NOT NULL COMMENT '开工时间',
  `end_date` DATE NOT NULL COMMENT '完工时间',
  `quality` VARCHAR(1024) NOT NULL COMMENT '质量目标',
  `safety` VARCHAR(1024) NOT NULL COMMENT '安全与文明施工目标',
  `cost` DECIMAL(20,2) NOT NULL COMMENT '成本目标（单位：元）',
  `memo` VARCHAR(1024) NOT NULL COMMENT '备注',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目目标';


-- -----------------------------------------------------
-- Table `worker_union`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`permission` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`permission` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限ID',
  `name` VARCHAR(32) NOT NULL COMMENT '名称',
  `value` VARCHAR(512) NOT NULL COMMENT '权限的值',
  `desc` VARCHAR(1024) NOT NULL COMMENT '描述',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worker_union`.`staff_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`staff_has_role` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`staff_has_role` (
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业员工ID',
  `role_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '角色ID',
  PRIMARY KEY (`staff_id`, `role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `worker_union`.`role_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`role_has_permission` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`role_has_permission` (
  `role_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '角色ID',
  `permission_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '权限ID',
  PRIMARY KEY (`role_id`, `permission_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `worker_union`.`project_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`project_application` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`project_application` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业人员ID',
  `type` VARCHAR(32) NOT NULL COMMENT '报建人员类型',
  PRIMARY KEY (`project_id`, `staff_id`),
  UNIQUE INDEX `uk_project_type` (`project_id` ASC, `type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目报建';


-- -----------------------------------------------------
-- Table `worker_union`.`team_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`team_role` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`team_role` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目角色ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `name` VARCHAR(32) NOT NULL COMMENT '名称',
  `type` VARCHAR(32) NOT NULL COMMENT '项目角色类型（项目经理：PROJECT_MANAGER，技术负责人：TECHNICAL_DIRECTOR，施工员：CONSTRUCTION_WORKER，质量员：QUALITY_WORKER，安全员：SAFETY_WORKER，预算员：BUDGETER，材料员：MATERIALMAN，机械员：MACHINIST，劳务员：LABOR_WORKER，资料员：DATA_PROCESSOR',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_type` (`company_id` ASC, `type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目角色';


-- -----------------------------------------------------
-- Table `worker_union`.`project_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`project_team` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`project_team` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业员工ID',
  `team_role_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目角色ID',
  PRIMARY KEY (`project_id`, `staff_id`),
  UNIQUE INDEX `uk_project_team_role` (`project_id` ASC, `team_role_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目团队搭建';


-- -----------------------------------------------------
-- Table `worker_union`.`team_role_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`team_role_has_permission` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`team_role_has_permission` (
  `team_role_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目角色ID',
  `permission_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '权限ID',
  PRIMARY KEY (`team_role_id`, `permission_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目角色权限';


-- -----------------------------------------------------
-- Table `worker_union`.`certificate_serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`certificate_serie` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`certificate_serie` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '证书系列ID',
  `name` VARCHAR(32) NOT NULL COMMENT '系列名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '证书系列';


-- -----------------------------------------------------
-- Table `worker_union`.`certificate_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`certificate_type` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`certificate_type` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '证书类型ID',
  `certificate_serie_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '证书系列ID',
  `certificate_serie_name` VARCHAR(32) NOT NULL COMMENT '证书系列名称',
  `name` VARCHAR(32) NOT NULL COMMENT '证书类型名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '证书类型';


-- -----------------------------------------------------
-- Table `worker_union`.`certificate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`certificate` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`certificate` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '证书ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '员工ID',
  `certificate_serie_id` BIGINT(20) UNSIGNED NOT NULL,
  `certificate_serie_name` VARCHAR(32) NOT NULL COMMENT '证书系列名称',
  `certificate_type_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '证书类型ID',
  `certificate_type_name` VARCHAR(32) NOT NULL COMMENT '证书类型名称',
  `num` VARCHAR(32) NOT NULL COMMENT '证书编号',
  `valid_date` DATE NOT NULL COMMENT '有效期',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '证书';


-- -----------------------------------------------------
-- Table `worker_union`.`supplier_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`supplier_grade` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`supplier_grade` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '供应商级别ID',
  `name` VARCHAR(32) NOT NULL COMMENT '供应商级别名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '供应商级别';


-- -----------------------------------------------------
-- Table `worker_union`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`supplier` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`supplier` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '供应商ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `name` VARCHAR(512) NOT NULL COMMENT '供应商名称',
  `num` VARCHAR(32) NOT NULL COMMENT '供应商编号',
  `supplier_grade_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '供应商级别ID',
  `supplier_grade_name` VARCHAR(32) NOT NULL COMMENT '供应商级别名称',
  `valid_date` DATE NOT NULL COMMENT '合同终止时间',
  `contact_person` VARCHAR(32) NOT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) NOT NULL COMMENT '联系方式',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_num` (`company_id` ASC, `num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '供应商';


-- -----------------------------------------------------
-- Table `worker_union`.`subcontractor_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`subcontractor_grade` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`subcontractor_grade` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分包商级别ID',
  `name` VARCHAR(32) NOT NULL COMMENT '分包商级别名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '分包商级别';


-- -----------------------------------------------------
-- Table `worker_union`.`subcontractor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`subcontractor` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`subcontractor` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分包商ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `name` VARCHAR(512) NOT NULL COMMENT '供应商名称',
  `num` VARCHAR(32) NOT NULL COMMENT '供应商编号',
  `subcontractor_grade_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '分包商级别ID',
  `subcontractor_grade_name` VARCHAR(32) NOT NULL COMMENT '分包商级别名称',
  `valid_date` DATE NOT NULL COMMENT '合作年限',
  `contact_person` VARCHAR(32) NOT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) NOT NULL COMMENT '联系方式',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_num` (`company_id` ASC, `num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '分包商';


-- -----------------------------------------------------
-- Table `worker_union`.`supplier_qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`supplier_qualification` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`supplier_qualification` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '供应商资质ID',
  `name` VARCHAR(32) NOT NULL COMMENT '供应商资质名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '供应商资质';


-- -----------------------------------------------------
-- Table `worker_union`.`supplier_has_supplier_qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`supplier_has_supplier_qualification` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`supplier_has_supplier_qualification` (
  `supplier_id` BIGINT(20) UNSIGNED NOT NULL,
  `supplier_qualification_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`supplier_id`, `supplier_qualification_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `worker_union`.`subcontractor_qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`subcontractor_qualification` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`subcontractor_qualification` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分包商资质ID',
  `name` VARCHAR(32) NOT NULL COMMENT '分包商资质名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '分包商资质';


-- -----------------------------------------------------
-- Table `worker_union`.`subcontractor_has_subcontractor_qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`subcontractor_has_subcontractor_qualification` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`subcontractor_has_subcontractor_qualification` (
  `subcontractor_id` BIGINT(20) UNSIGNED NOT NULL,
  `subcontractor_qualification_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`subcontractor_id`, `subcontractor_qualification_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `worker_union`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`contract` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`contract` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '合同ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `name` VARCHAR(512) NOT NULL COMMENT '名称',
  `num` VARCHAR(32) NOT NULL COMMENT '编号',
  `type` VARCHAR(32) NOT NULL COMMENT '类型',
  `part_a` VARCHAR(512) NOT NULL COMMENT '甲方名称',
  `part_b` VARCHAR(512) NOT NULL COMMENT '乙方名称',
  `sign_date` DATE NOT NULL COMMENT '签约时间',
  `money` DECIMAL(20,2) NOT NULL COMMENT '金额',
  `duty_department` VARCHAR(32) NOT NULL COMMENT '责任部门',
  `content_abstract` VARCHAR(1024) NOT NULL COMMENT '内容摘要',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_num` (`company_id` ASC, `num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '合同';


-- -----------------------------------------------------
-- Table `worker_union`.`supplier_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`supplier_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`supplier_attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `supplier_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '供应商ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（INFORMATION）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '供应商附件';


-- -----------------------------------------------------
-- Table `worker_union`.`subcontractor_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`subcontractor_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`subcontractor_attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `subcontractor_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '分包商ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（INFORMATION）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '分包商附件';


-- -----------------------------------------------------
-- Table `worker_union`.`material_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_type` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_type` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '材料类型ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `name` VARCHAR(512) NOT NULL COMMENT '名称',
  `num` VARCHAR(32) NOT NULL COMMENT '编号',
  `model` VARCHAR(32) NOT NULL COMMENT '规格型号',
  `unit` VARCHAR(32) NOT NULL COMMENT '计量单位',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_num` (`company_id` ASC, `num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '材料类型';


-- -----------------------------------------------------
-- Table `worker_union`.`material_type_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_type_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_type_attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `material_type_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '材料类型ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（INFORMATION）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '材料类型附件';


-- -----------------------------------------------------
-- Table `worker_union`.`material_headquarters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_headquarters` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_headquarters` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '总部材料ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `name` VARCHAR(512) NOT NULL COMMENT '名称',
  `num` VARCHAR(32) NOT NULL COMMENT '编号',
  `model` VARCHAR(32) NOT NULL COMMENT '规格型号',
  `unit` VARCHAR(32) NOT NULL COMMENT '计量单位',
  `amount` DECIMAL(20,5) NOT NULL COMMENT '数量',
  `amount_freeze` DECIMAL(20,5) NOT NULL COMMENT '冻结的数量',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_num` (`company_id` ASC, `num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '总部材料';


-- -----------------------------------------------------
-- Table `worker_union`.`material_headquarters_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_headquarters_order` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_headquarters_order` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '总部材料订单ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `target_project_id` BIGINT(20) UNSIGNED NULL COMMENT '目标对象ID',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '出入库员工ID',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '出入库员工名称',
  `batch_no` VARCHAR(32) NOT NULL COMMENT '批次号（系统生成，以HQB开头）',
  `money` DECIMAL(20,2) NOT NULL COMMENT '金额',
  `type` VARCHAR(32) NOT NULL COMMENT '类型（出库：EXPORT，入库：IMPORT）',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_company_batch_no` (`company_id` ASC, `batch_no` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '总部材料批次';


-- -----------------------------------------------------
-- Table `worker_union`.`material_headquarters_order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_headquarters_order_detail` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_headquarters_order_detail` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '总部材料订单详情ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `material_headquarters_order_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '总部材料订单ID',
  `name` VARCHAR(512) NOT NULL COMMENT '名称',
  `num` VARCHAR(32) NOT NULL COMMENT '编号',
  `model` VARCHAR(32) NOT NULL COMMENT '规格型号',
  `unit` VARCHAR(32) NOT NULL COMMENT '计量单位',
  `amount` DECIMAL(20,5) NOT NULL COMMENT '数量',
  `price` DECIMAL(20,2) NOT NULL COMMENT '单价',
  `money` DECIMAL(20,2) NOT NULL COMMENT '金额',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '总部材料订单详情';


-- -----------------------------------------------------
-- Table `worker_union`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目材料ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `name` VARCHAR(512) NOT NULL COMMENT '名称',
  `num` VARCHAR(32) NOT NULL COMMENT '编号',
  `model` VARCHAR(32) NOT NULL COMMENT '规格型号',
  `unit` VARCHAR(32) NOT NULL COMMENT '计量单位',
  `amount` DECIMAL(20,5) NOT NULL COMMENT '数量',
  `amount_freeze` DECIMAL(20,5) NULL COMMENT '冻结的数量',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_project_num` (`num` ASC, `project_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目材料';


-- -----------------------------------------------------
-- Table `worker_union`.`material_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_order` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_order` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目材料订单ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '出入库员工ID',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '出入库员工名称',
  `batch_no` VARCHAR(32) NOT NULL COMMENT '批次号（系统生成，以B开头）',
  `money` DECIMAL(20,2) NOT NULL COMMENT '金额',
  `type` VARCHAR(32) NOT NULL COMMENT '类型（出库：EXPORT，入库：IMPORT）',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_project_batch_no` (`batch_no` ASC, `project_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目材料批次';


-- -----------------------------------------------------
-- Table `worker_union`.`material_order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_order_detail` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_order_detail` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目材料订单详情ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `material_order_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目材料订单ID',
  `name` VARCHAR(512) NOT NULL COMMENT '名称',
  `num` VARCHAR(32) NOT NULL COMMENT '编号',
  `model` VARCHAR(32) NOT NULL COMMENT '规格型号',
  `unit` VARCHAR(32) NOT NULL COMMENT '计量单位',
  `amount` DECIMAL(20,5) NOT NULL COMMENT '数量',
  `price` DECIMAL(20,2) NOT NULL COMMENT '单价',
  `money` DECIMAL(20,2) NOT NULL COMMENT '金额',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目材料订单详情';


-- -----------------------------------------------------
-- Table `worker_union`.`material_transfer_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_transfer_application` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_transfer_application` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '材料转库申请ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL,
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '申请人ID',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '申请人姓名',
  `export_project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '出库项目组ID',
  `import_project_id` BIGINT(20) UNSIGNED NULL COMMENT '进库项目组ID',
  `money` DECIMAL(20,2) NOT NULL COMMENT '金额',
  `type` VARCHAR(32) NOT NULL COMMENT '类型（转项目组：TO_PROJECT，转总部：TO_HEADQUARTERS）',
  `status` VARCHAR(32) NOT NULL COMMENT '申请状态（通过：PASS，驳回：FAIL，未审核：UNDETERMINED）',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '材料转库申请';


-- -----------------------------------------------------
-- Table `worker_union`.`material_transfer_application_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`material_transfer_application_detail` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`material_transfer_application_detail` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '转库申请详情ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `material_transfer_application_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '转库申请ID',
  `name` VARCHAR(512) NOT NULL COMMENT '名称',
  `num` VARCHAR(32) NOT NULL COMMENT '编号',
  `model` VARCHAR(32) NOT NULL COMMENT '规格型号',
  `unit` VARCHAR(32) NOT NULL COMMENT '计量单位',
  `amount` DECIMAL(20,5) NOT NULL COMMENT '数量',
  `price` DECIMAL(20,2) NOT NULL COMMENT '单价',
  `money` DECIMAL(20,2) NOT NULL COMMENT '金额',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '转库申请详情';


-- -----------------------------------------------------
-- Table `worker_union`.`attachment_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`attachment_audit` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`attachment_audit` (
  `attachment_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `status` VARCHAR(32) NOT NULL COMMENT '状态（未审核：UNDETERMINED，通过：PASS，驳回：FAIL）',
  `opinion` VARCHAR(1024) NOT NULL COMMENT '审核意见',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`attachment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '附件审核';


-- -----------------------------------------------------
-- Table `worker_union`.`cost_analysis_item_deepen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`cost_analysis_item_deepen` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`cost_analysis_item_deepen` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '成本分析项深化ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `name` VARCHAR(32) NOT NULL COMMENT '成本项名称',
  `type` VARCHAR(32) NOT NULL COMMENT '成本类型（直接成本：DIRECT_COST，间接成本：INDIRECT_COST，指定分包成本：SUBCONTRACT_COST，税额：TAX_COST）',
  `price` DECIMAL(20,2) NOT NULL COMMENT '单价（单位：元）',
  `amount` DECIMAL(20,5) NOT NULL COMMENT '数量',
  `unit` VARCHAR(32) NOT NULL COMMENT '单位',
  `cost` DECIMAL(20,2) NOT NULL COMMENT '成本花费（单位：元）',
  `memo` VARCHAR(1024) NOT NULL COMMENT '备注',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '项目成本分析';


-- -----------------------------------------------------
-- Table `worker_union`.`purchase_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`purchase_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`purchase_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '采购条目ID',
  `name` VARCHAR(32) NOT NULL COMMENT '名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '采购条目';


-- -----------------------------------------------------
-- Table `worker_union`.`fund_plan_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`fund_plan_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`fund_plan_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '资金计划条目ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `purchase_item_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '采购条目ID',
  `purchase_item_name` VARCHAR(32) NOT NULL COMMENT '采购条目名称',
  `cost_analysis_item_deepen_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '关联成本分析深化项',
  `requirement` VARCHAR(32) NOT NULL COMMENT '需求说明',
  `money` DECIMAL(20,2) NOT NULL COMMENT '资金（单位：元）',
  `expected_purchase_date` DATE NOT NULL COMMENT '预计采购时间',
  `expected_service_date` DATE NOT NULL COMMENT '预计使用时间',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '资金计划条目';


-- -----------------------------------------------------
-- Table `worker_union`.`final_settlement_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`final_settlement_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`final_settlement_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '决算条目ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `subproject_name` VARCHAR(512) NOT NULL COMMENT '名称',
  `submit_money` DECIMAL(20,2) NOT NULL COMMENT '送审金额（单位：元）',
  `checked_money` DECIMAL(20,2) NOT NULL COMMENT '核定金额（单位：元）',
  `increased_money` DECIMAL(20,2) NOT NULL COMMENT '核减金额（单位：元）',
  `decreased_money` DECIMAL(20,2) NOT NULL COMMENT '核增金额（单位：元）',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '决算条目';


-- -----------------------------------------------------
-- Table `worker_union`.`business_capacity_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`business_capacity_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`business_capacity_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '经营管理ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `year` INT UNSIGNED NOT NULL COMMENT '年份',
  `month` INT UNSIGNED NOT NULL COMMENT '月份',
  `product_value` DECIMAL(20,2) NOT NULL COMMENT '产值（单位：元）',
  `checked_value` DECIMAL(20,2) NOT NULL COMMENT '核定产值',
  `is_checked` TINYINT(1) NOT NULL COMMENT '是否核定标识',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人ID',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_project_year_month` (`project_id` ASC, `year` ASC, `month` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '经营产能';


-- -----------------------------------------------------
-- Table `worker_union`.`product_capacity_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`product_capacity_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`product_capacity_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '生产管理ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `year` INT UNSIGNED NOT NULL COMMENT '年份',
  `month` INT UNSIGNED NOT NULL COMMENT '月份',
  `expected_value` INT UNSIGNED NOT NULL COMMENT '预期进度（单位：天）',
  `actual_value` INT UNSIGNED NOT NULL COMMENT '实际进度（单位：天）',
  `checked_value` INT UNSIGNED NOT NULL COMMENT '核定进度（单位：天）',
  `is_checked` TINYINT(1) NOT NULL COMMENT '是否核定标识',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人ID',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_project_year_month` (`project_id` ASC, `year` ASC, `month` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '生产管理';


-- -----------------------------------------------------
-- Table `worker_union`.`safety_check_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`safety_check_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`safety_check_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '安全检查ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `inspect_date` DATE NOT NULL COMMENT '检查日期',
  `inspect_record` VARCHAR(1024) NOT NULL COMMENT '检查记录',
  `rectify_opinion` VARCHAR(1024) NOT NULL COMMENT '整改意见',
  `project_feedback` VARCHAR(1024) NOT NULL COMMENT '项目反馈',
  `evaluate_date` DATE NOT NULL COMMENT '评定日期',
  `evaluate` VARCHAR(1024) NOT NULL COMMENT '检查评定',
  `rectify_status` VARCHAR(32) NOT NULL COMMENT '整改状态（整改通过：PASS，整改：RECTIFY，整改申请审核：VERIFY）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '检查人ID',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '检查人名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '安全检查';


-- -----------------------------------------------------
-- Table `worker_union`.`quality_check_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`quality_check_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`quality_check_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '质量检查ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `inspect_date` DATE NOT NULL COMMENT '检查日期',
  `inspect_record` VARCHAR(1024) NOT NULL COMMENT '检查记录',
  `rectify_opinion` VARCHAR(1024) NOT NULL COMMENT '整改意见',
  `project_feedback` VARCHAR(1024) NOT NULL COMMENT '项目反馈',
  `evaluate_date` DATE NOT NULL COMMENT '评定日期',
  `evaluate` VARCHAR(1024) NOT NULL COMMENT '检查评定',
  `rectify_status` VARCHAR(32) NOT NULL COMMENT '整改状态（整改通过：PASS，整改：RECTIFY，整改申请审核：VERIFY）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '检查人ID',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '检查人名称',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '质量检查';


-- -----------------------------------------------------
-- Table `worker_union`.`safety_check_item_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`safety_check_item_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`safety_check_item_attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `safety_check_item_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '安全检查项ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（记录：RECORD，反馈：CALLBACK）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '安全检查项附件';


-- -----------------------------------------------------
-- Table `worker_union`.`quality_check_item_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`quality_check_item_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`quality_check_item_attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `quality_check_item_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '质量检查项ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（附件资料：INFORMATION）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '安全检查项附件';


-- -----------------------------------------------------
-- Table `worker_union`.`resource_implement_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`resource_implement_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`resource_implement_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '资源落实项ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `fund_plan_item_id` BIGINT(20) UNSIGNED NULL COMMENT '资金计划项ID',
  `subcontractor_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '分包商ID',
  `subcontractor_name` VARCHAR(512) NOT NULL COMMENT '分包商名称',
  `purchase_item_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '采购条目ID',
  `purchase_item_name` VARCHAR(32) NOT NULL COMMENT '采购条目名称',
  `contract_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '关联合同ID',
  `contract_name` VARCHAR(512) NOT NULL COMMENT '合同名称',
  `contract_num` VARCHAR(32) NOT NULL COMMENT '合同编号',
  `name` VARCHAR(32) NOT NULL COMMENT '名称',
  `unit` VARCHAR(32) NOT NULL COMMENT '单位',
  `price` DECIMAL(20,2) NOT NULL COMMENT '单价（单位：元）',
  `amount` DECIMAL(20,5) NOT NULL COMMENT '数量',
  `money` DECIMAL(20,2) NOT NULL COMMENT '实际金额',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '资源落实项';


-- -----------------------------------------------------
-- Table `worker_union`.`settlement_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`settlement_item` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`settlement_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `resource_implement_item_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '资源落实项ID',
  `subcontractor_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '分包商ID',
  `subcontractor_name` VARCHAR(512) NOT NULL COMMENT '分包商名称',
  `purchase_item_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '采购条目ID',
  `purchase_item_name` VARCHAR(32) NOT NULL COMMENT '采购条目名称',
  `year` INT UNSIGNED NOT NULL COMMENT '年份',
  `month` INT UNSIGNED NOT NULL COMMENT '月份',
  `money` DECIMAL(20,2) NOT NULL COMMENT '当月结算值（单位：元）',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_resource_implement_item_year_month` (`resource_implement_item_id` ASC, `year` ASC, `month` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '结算项';


-- -----------------------------------------------------
-- Table `worker_union`.`internal_settlement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`internal_settlement` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`internal_settlement` (
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `duration` INT NOT NULL COMMENT '工期目标完成情况',
  `quality` VARCHAR(1024) NOT NULL COMMENT '质量目标完成情况',
  `safety` VARCHAR(1024) NOT NULL COMMENT '安全与文明施工目标完成情况',
  `cost` DECIMAL(20,2) NOT NULL COMMENT '成本目标（单位：元）完成情况',
  `internal_cost` DECIMAL(20,2) NOT NULL COMMENT '内部结算金额',
  `extra_award` DECIMAL(20,2) NOT NULL COMMENT '额外奖励金额',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '结算评估';


-- -----------------------------------------------------
-- Table `worker_union`.`final_settlement_item_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`final_settlement_item_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`final_settlement_item_attachment` (
  `final_settlement_item_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '竣工结算项ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `project_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '项目ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（附件资料：INFORMATION）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`final_settlement_item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '决算条目附件';


-- -----------------------------------------------------
-- Table `worker_union`.`contract_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`contract_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`contract_attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `contract_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '合同ID',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（INFORMATION）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '合同附件';


-- -----------------------------------------------------
-- Table `worker_union`.`certificate_attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `worker_union`.`certificate_attachment` ;

CREATE TABLE IF NOT EXISTS `worker_union`.`certificate_attachment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `company_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '企业ID',
  `certificate_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '证书id',
  `name` VARCHAR(512) NOT NULL COMMENT '附件文件名',
  `content_type` VARCHAR(512) NOT NULL COMMENT '文件contentType属性',
  `size` BIGINT(20) UNSIGNED NOT NULL COMMENT '文件尺寸（字节）',
  `path` VARCHAR(1024) NOT NULL COMMENT '文件路径',
  `type` VARCHAR(32) NOT NULL COMMENT '附件类型（INFORMATION）',
  `staff_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '创建人',
  `staff_name` VARCHAR(32) NOT NULL COMMENT '创建人姓名',
  `cst_create` DATETIME NOT NULL COMMENT '创建时间',
  `cst_modified` DATETIME NOT NULL COMMENT '修改时间',
  `is_del` TINYINT(1) NOT NULL COMMENT '删除标识',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '证书附件';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
